services:
  database:
    container_name: database_todo
    image: postgres:latest
    env_file: .env
    ports:
      - 3333:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: backend_todo
    build:
      context: ./backend
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app

  frontend:
    container_name: frontend_todo
    build:
      context: ./frontend
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - database
      - backend
    volumes:
      - ./frontend:/app

volumes:
  pgdata:
